export const [
  FETCH_GLOBAL_DATA_SUCCESS,
  FETCH_GLOBAL_DATA_FAILED,
  FETCH_COUNTRY_CONFIRMED_SUCCESS,
  FETCH_COUNTRY_CONFIRMED_FAILED,
  FETCH_COUNTRY_DEATHS_SUCCESS,
  FETCH_COUNTRY_DEATHS_FAILED,
  FETCH_COUNTRY_RECOVERED_SUCCESS,
  FETCH_COUNTRY_RECOVERED_FAILED
] = [
  "FETCH_GLOBAL_DATA_SUCCESS",
  "FETCH_GLOBAL_DATA_FAILED",
  "FETCH_COUNTRY_CONFIRMED_SUCCESS",
  "FETCH_COUNTRY_CONFIRMED_FAILED",
  "FETCH_COUNTRY_DEATHS_SUCCESS",
  "FETCH_COUNTRY_DEATHS_FAILED",
  "FETCH_COUNTRY_RECOVERED_SUCCESS",
  "FETCH_COUNTRY_RECOVERED_FAILED"
];
